font_family      IoskeleyMonoTerm Nerd Font
font_size        15.0

cursor_shape     underline

window_padding_width 10

hide_window_decorations titlebar-only
macos_option_as_alt yes
term xterm-256color

# Nord
background #2e3440
foreground #d8dee9
cursor     #d8dee9
cursor_text_color #2e3440
selection_background #434c5e
selection_foreground #eceff4

color0  #3b4252
color8  #4c566a
color1  #bf616a
color9  #bf616a
color2  #a3be8c
color10 #a3be8c
color3  #ebcb8b
color11 #ebcb8b
color4  #81a1c1
color12 #81a1c1
color5  #b48ead
color13 #b48ead
color6  #88c0d0
color14 #8fbcbb
color7  #e5e9f0
color15 #eceff4

map ctrl+n new_os_window
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map ctrl+a>h launch --location=vsplit
map ctrl+a>j launch --location=hsplit
map ctrl+a>k launch --location=hsplit
map ctrl+a>l launch --location=vsplit
map ctrl+a>f toggle_layout stack
map ctrl+a>n next_tab
map ctrl+a>p previous_tab
map cmd+r load_config_file
